# Generated by Django 3.1.4 on 2021-01-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userloyaltystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='donated_loyalty_points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earned_loyalty_points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='going_to_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_loyalty_points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserLoyaltyStatus',
        ),
    ]
