# Generated by Django 3.1.4 on 2021-01-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20210117_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=55)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('header_image', models.ImageField(upload_to='')),
                ('intro_paragraph', models.TextField(max_length=300)),
                ('subheading_1', models.CharField(max_length=55)),
                ('blog_content_1', models.TextField()),
                ('subheading_2', models.CharField(max_length=55)),
                ('blog_content_2', models.TextField()),
                ('subheading_3', models.CharField(blank=True, max_length=55, null=True)),
                ('blog_content_3', models.TextField(blank=True, null=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='products.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
