# Generated by Django 3.1.4 on 2021-01-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_category',
        ),
    ]
