# Generated by Django 3.1.4 on 2021-01-20 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content_1',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content_2',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content_3',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='intro_paragraph',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
