# Generated by Django 3.1.4 on 2021-01-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
