# Generated by Django 3.1.4 on 2020-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='short_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
