# Generated by Django 3.1.4 on 2020-12-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
