# Generated by Django 3.1.4 on 2021-01-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201231_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=375)),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_eco', models.BooleanField(blank=True, default=True, null=True)),
                ('is_crueltyfree', models.BooleanField(blank=True, default=True, null=True)),
                ('is_vegan', models.BooleanField(blank=True, default=True, null=True)),
                ('is_organic', models.BooleanField(blank=True, default=True, null=True)),
                ('is_natural', models.BooleanField(blank=True, default=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
